MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/abby/Repositories/maskrcnn-benchmark/pretrained_model/e2e_mask_rcnn_R_50_FPN_1x_city.pth"
  # WEIGHT: "/home/abby/Repositories/maskrcnn-benchmark/workspace/kitti_pretrained_model/model_0090000.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  ROI_BOX3D_HEAD:
    FEATURE_EXTRACTOR: "Box3dFeatureExtractor"
    POINT_CLOUD_FEATURE_EXTRACTOR: "Box3dPCFeatureExtractor"
    SHARE_BOX_FEATURE_EXTRACTOR: False
    PREDICTOR: "Box3DPredictor"
    PREDICTOR_DIMENSION: "Box3dDimPredictor"
    PREDICTOR_ROTATION_CONFIDENCES: "RotationConfidencePredictor"
    PREDICTOR_ROTATION_REGRESSION: "RotationRegressionPredictor"
    PREDICTOR_LOCALIZATION_CONV: "Box3dLocConvPredictor"
    PREDICTOR_LOCALIZATION_PC: "Box3dLocPCPredictor"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 1
    PREDICTORS_HEAD_DIM: 512
    PREDICTORS_DIMENSION_HEAD_DIM: 512
    PREDICTORS_ROTATION_CONFIDENCES_HEAD_DIM: 256
    PREDICTORS_ROTATION_REGRESSION_HEAD_DIM: 256
    ROTATION_BIN: 2
    ROTATION_OVERLAP: 0.1
    POINTCLOUD_OUT_CHANNELS: 3
    BBOX3D_REG_WEIGHTS: (5., 5., 5., 10., 10., 10.)
  MASK_ON: False
  BOX3D_ON: True
  BOX3D_DIMENSION_ON: True
  BOX3D_ROTATION_CONFIDENCES_ON: True
  BOX3D_ROTATION_REGRESSION_ON: True
  BOX3D_LOCALIZATION_ON: True
DATASETS:
  #TRAIN: ("kitti_fine_instanceonly_seg_train",)
  #TEST: ("kitti_fine_instanceonly_seg_val",)
  TRAIN: ("kitti_3d_train",)
  TEST: ("kitti_3d_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 150000
TEST:
  IMS_PER_BATCH: 1
